import Link from "next/link";

import { requireUser } from "@/lib/authz";
import { prisma } from "@/lib/prisma";

import { CustomerWorkspaceShell } from "../customer-workspace-shell";

export default async function CustomerSettingsPage() {
  const user = await requireUser();
  const profile = await prisma.user.findUniqueOrThrow({ where: { id: user.id }, select: { displayName: true, email: true, phoneNumber: true, verificationStatus: true, primaryLocation: { select: { name: true, state: true } }, customerProfile: { select: { preferredLanguages: true } } } });
  return <CustomerWorkspaceShell active="Settings" title="Settings" subtitle="Manage your account preferences and customer profile.">
    <section className="grid gap-3 xl:grid-cols-[240px_minmax(0,1fr)]">
      <aside className="rounded-2xl border border-white/80 bg-white/94 p-3 shadow-sm"><nav className="space-y-1 text-xs font-bold"><span className="block rounded-lg bg-violet-600 px-3 py-2 text-white">Account</span><span className="block rounded-lg px-3 py-2 text-slate-600">Notifications</span><span className="block rounded-lg px-3 py-2 text-slate-600">Security</span><span className="block rounded-lg px-3 py-2 text-slate-600">Preferences</span><span className="block rounded-lg px-3 py-2 text-slate-600">Billing</span></nav></aside>
      <div className="space-y-3"><section className="rounded-2xl border border-white/80 bg-white/94 p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-sm font-black">Profile Information</h2><Link href="/account" className="rounded-lg border border-slate-200 px-3 py-1.5 text-[10px] font-black">Edit</Link></div><dl className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><div><dt className="text-[10px] font-bold text-slate-400">Full name</dt><dd className="mt-1 font-black">{profile.displayName || "Not set"}</dd></div><div><dt className="text-[10px] font-bold text-slate-400">Email</dt><dd className="mt-1 font-black">{profile.email || "Not set"}</dd></div><div><dt className="text-[10px] font-bold text-slate-400">Phone</dt><dd className="mt-1 font-black">{profile.phoneNumber || "Not set"}</dd></div><div><dt className="text-[10px] font-bold text-slate-400">Location</dt><dd className="mt-1 font-black">{profile.primaryLocation ? `${profile.primaryLocation.name}, ${profile.primaryLocation.state}` : "Not set"}</dd></div><div><dt className="text-[10px] font-bold text-slate-400">Verification</dt><dd className="mt-1 font-black">{profile.verificationStatus.replaceAll("_", " ")}</dd></div><div><dt className="text-[10px] font-bold text-slate-400">Languages</dt><dd className="mt-1 font-black">{profile.customerProfile?.preferredLanguages.join(", ") || "Not set"}</dd></div></dl></section><section className="rounded-2xl border border-white/80 bg-white/94 p-4 shadow-sm"><h2 className="text-sm font-black">Account Preferences</h2><div className="mt-3 divide-y divide-slate-100">{[["Email notifications", "Receive project, message and order updates", true], ["SMS notifications", "Receive important account alerts", true], ["Marketing emails", "Product news and marketplace offers", false]].map(([title, detail, enabled]) => <div key={String(title)} className="flex items-center justify-between gap-4 py-3"><div><p className="text-xs font-black">{title}</p><p className="text-[10px] text-slate-400">{detail}</p></div><button type="button" aria-pressed={Boolean(enabled)} className={`relative h-6 w-11 rounded-full ${enabled ? "bg-violet-600" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${enabled ? "right-1" : "left-1"}`} /></button></div>)}</div></section><section className="rounded-2xl border border-rose-200 bg-white/94 p-4 shadow-sm"><h2 className="text-sm font-black text-rose-700">Danger Zone</h2><div className="mt-3 flex items-center justify-between gap-4"><div><p className="text-xs font-black">Delete account</p><p className="text-[10px] text-slate-400">Permanent account deletion will be enabled during the production account phase.</p></div><button type="button" disabled className="rounded-lg bg-rose-100 px-3 py-2 text-[10px] font-black text-rose-600 opacity-60">Delete</button></div></section></div>
    </section>
  </CustomerWorkspaceShell>;
}
