"use client";

import { useActionState, useState } from "react";
import { useFormStatus } from "react-dom";

import { ROLE_DESCRIPTIONS, ROLE_LABELS, PUBLIC_ONBOARDING_ROLES, type PublicOnboardingRole } from "@/lib/onboarding";
import { completeOnboarding, type OnboardingState } from "./actions";

function SubmitButton() { const { pending } = useFormStatus(); return <button disabled={pending} className="min-h-12 rounded-full bg-fuchsia-400 px-6 py-3 font-black text-[#14051d] hover:bg-fuchsia-300 focus:outline-none focus-visible:ring-2 focus-visible:ring-fuchsia-100 disabled:opacity-60">{pending ? "Completing onboarding…" : "Complete onboarding"}</button>; }
const field = "min-h-11 w-full rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-white outline-none placeholder:text-white/40 focus:border-fuchsia-200 focus:ring-2 focus:ring-fuchsia-200/40";

export function OnboardingForm({ locations, initialName }: { locations: { id: string; name: string; district: string; state: string; country: string }[]; initialName: string }) {
  const [state, action] = useActionState<OnboardingState | undefined, FormData>(completeOnboarding, undefined);
  const [role, setRole] = useState<PublicOnboardingRole>("CUSTOMER");
  const err = (name: string) => state?.fieldErrors?.[name] ? <p className="mt-2 text-sm text-rose-200" role="alert">{state.fieldErrors[name]}</p> : null;
  return <form action={action} className="space-y-8">
    {state?.error ? <p className="rounded-2xl border border-rose-300/30 bg-rose-500/10 p-3 text-sm text-rose-100" role="alert">{state.error}</p> : null}
    <fieldset><legend className="text-lg font-black">Choose your role</legend><div className="mt-4 grid gap-3 sm:grid-cols-2">{PUBLIC_ONBOARDING_ROLES.map((item) => <label key={item} className="cursor-pointer rounded-3xl border border-white/10 bg-white/[0.04] p-4 has-[:checked]:border-fuchsia-200 has-[:checked]:bg-fuchsia-400/10"><input className="sr-only" type="radio" name="role" value={item} checked={role === item} onChange={() => setRole(item)} /><span className="font-bold text-white">{ROLE_LABELS[item]}</span><span className="mt-1 block text-sm text-white/65">{ROLE_DESCRIPTIONS[item]}</span></label>)}</div>{err("role")}</fieldset>
    <section className="grid gap-5 md:grid-cols-2"><div><label htmlFor="displayName" className="text-sm font-bold text-white">Display name</label><input id="displayName" name="displayName" defaultValue={initialName} className={field} />{err("displayName")}</div><div><label htmlFor="phoneNumber" className="text-sm font-bold text-white">Phone (optional)</label><input id="phoneNumber" name="phoneNumber" inputMode="tel" className={field} />{err("phoneNumber")}</div></section>
    <section><label htmlFor="locationId" className="text-sm font-bold text-white">Primary location</label>{locations.length ? <select id="locationId" name="locationId" className={field}>{locations.map((location) => <option className="bg-[#12091d]" key={location.id} value={location.id}>{location.name} — {location.district}, {location.state}, {location.country}</option>)}</select> : <p className="rounded-2xl border border-amber-200/25 bg-amber-300/10 p-4 text-sm text-amber-100">No active Yartong locations are available yet.</p>}{err("locationId")}</section>
    {role === "SKILLED_PROVIDER" ? <section className="grid gap-5 md:grid-cols-2"><div><label htmlFor="headline" className="text-sm font-bold">Trade or service summary</label><input id="headline" name="headline" className={field} placeholder="Masonry and repair specialist" />{err("headline")}</div><div><label htmlFor="experienceYears" className="text-sm font-bold">Experience years</label><input id="experienceYears" name="experienceYears" type="number" min="0" max="60" className={field} />{err("experienceYears")}</div><div className="md:col-span-2"><label htmlFor="skills" className="text-sm font-bold">Skills (comma separated)</label><input id="skills" name="skills" className={field} placeholder="Masonry, plastering, repairs" />{err("skills")}</div></section> : null}
    {role === "LABOURER" ? <section className="grid gap-5 md:grid-cols-2"><div><label htmlFor="labSkills" className="text-sm font-bold">Skills (comma separated)</label><input id="labSkills" name="skills" className={field} placeholder="Site support, loading, concrete mixing" />{err("skills")}</div><div><label htmlFor="labExp" className="text-sm font-bold">Experience years</label><input id="labExp" name="experienceYears" type="number" min="0" max="60" className={field} />{err("experienceYears")}</div><div className="md:col-span-2"><label htmlFor="labHeadline" className="text-sm font-bold">Availability summary (optional)</label><input id="labHeadline" name="headline" className={field} placeholder="Available for site support in Senapati" /></div></section> : null}
    {role === "CONTRACTOR" ? <section className="grid gap-5 md:grid-cols-2"><div><label htmlFor="businessName" className="text-sm font-bold">Business name</label><input id="businessName" name="businessName" className={field} />{err("businessName")}</div><div><label htmlFor="teamSize" className="text-sm font-bold">Team size</label><input id="teamSize" name="teamSize" type="number" min="1" max="500" className={field} />{err("teamSize")}</div><div><label htmlFor="contractorHeadline" className="text-sm font-bold">Project/service summary</label><input id="contractorHeadline" name="headline" className={field} />{err("headline")}</div><div><label htmlFor="projectTypes" className="text-sm font-bold">Project types (comma separated)</label><input id="projectTypes" name="skills" className={field} placeholder="Residential, renovation" /></div></section> : null}
    {role === "MATERIAL_SUPPLIER" ? <section className="grid gap-5 md:grid-cols-2"><div><label htmlFor="supplierBusiness" className="text-sm font-bold">Business name</label><input id="supplierBusiness" name="businessName" className={field} />{err("businessName")}</div><div><label htmlFor="materialCategories" className="text-sm font-bold">Material categories</label><input id="materialCategories" name="materialCategories" className={field} placeholder="Cement, sand, steel" />{err("materialCategories")}</div><div className="md:col-span-2"><label htmlFor="supplierSummary" className="text-sm font-bold">Business summary (optional)</label><input id="supplierSummary" name="supplierSummary" className={field} /></div><label className="flex min-h-11 items-center gap-3 rounded-2xl border border-white/10 p-3"><input type="checkbox" name="deliveryAvailable" /> Delivery available</label></section> : null}
    <SubmitButton />
  </form>;
}
